# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: bandre <bandre@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/07/13 01:26:02 by nithramir         #+#    #+#              #
#    Updated: 2018/11/26 22:26:57 by bandre           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	echo "nothing to do to build js files"

fclean: clean
	echo "no binary to delete"

clean:
	rm -f Grace_kid.js

re: fclean