# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: nithramir <nithramir@student.42.fr>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/07/13 01:26:02 by nithramir         #+#    #+#              #
#    Updated: 2018/07/13 01:33:06 by nithramir        ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	echo "nothing to do to build js files"

clean:
	rm -f Grace_kid.js
	rm -f Sully_*
