# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: nithramir <nithramir@student.42.fr>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/07/12 22:04:46 by nithramir         #+#    #+#              #
#    Updated: 2018/07/12 22:25:20 by nithramir        ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	gcc Colleen.c -o Colleen
	gcc Grace.c -o Grace
	gcc Sully.c -o Sully

clean:
	rm -f Grace_kid.c
	rm -f Sully_*

fclean: clean
	rm -f Colleen
	rm -f Grace
	rm -f Sully