# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: bandre <bandre@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/07/12 22:04:46 by nithramir         #+#    #+#              #
#    Updated: 2018/11/22 16:41:12 by bandre           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all: Colleen Grace Sully

Colleen:
	gcc Colleen.c -o Colleen

Grace:
	gcc Grace.c -o Grace

Sully:
	gcc Sully.c -o Sully

clean:
	rm -f Grace_kid.c
	rm -f Sully_*

fclean: clean
	rm -f Colleen
	rm -f Grace
	rm -f Sully

re:  fclean all